Distribution\BackendBundle\Entity\Item:
    type: entity
    table: null
    repositoryClass: Distribution\BackendBundle\Entity\ItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
    lifecycleCallbacks: {  }
