Distribution\BackendBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: Distribution\BackendBundle\Entity\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        author:
            type: string
            length: 255
        body:
            type: text
    lifecycleCallbacks: {  }
